documentation
nat/ghtop pull request #6
Opened 2020-12-04 21:57 UTC by ROZBEH

2020-12-04 22:27 UTC, logankilpatrick requested changes
Putting your GitHub access token in a txt file within a repo is definitely not recommended.

2020-12-04 23:06 UTC, ROZBEH commented
Please refer to https://github.com/nat/ghtop/blob/master/ghtop.py#L26

Also, `ghtoken.txt` is just saved locally.

2020-12-05 01:33 UTC, nat approved these changes

2020-12-05 01:33 UTC, nat commented on README.md
> +- Finaly, in order to see in realtime what's happening, run the following command from your terminal. `python ghtop.py tail` Feel free to pick one of the following options `quad`, `users`, `simple`,
```suggestion
### Getting Started

- Install the `emoji` and `enlighten` packages with pip
- [Create a GitHub PAT](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token) and put it in `ghtoken.txt`
```

2020-12-05 01:34 UTC, merged